### ISSUE TITLE
Failed Request Tracing

### ISSUE THREAD

**Issue by jawn** [angularsen/AspNetHttpLogger#5]
Failed Request Tracing can be an alternative solution to log request/responses:

https://docs.microsoft.com/en-us/iis/troubleshoot/using-failed-request-tracing/troubleshoot-with-failed-request-tracing

It would be helpful to add this to the README.

**Comment by angularsen** [comment]
Hi and thanks, you're right failed request tracing helps when running IIS to get details about failed requests, but to my knowledge:

A) It does not provide the body of the request
B) It only works for failed requests, I was trying to log both successes and errors

This repo has not been updated in a long time and I just added a warning to the README that this does not fully work with OWIN, which was introduced in Mvc5. I was no longer able to read the request/response body. See #3 for possible workaround.

**Comment by jawn** [comment]
Hi,

A) The following setting will also log the full request and response body:
![image](https://user-images.githubusercontent.com/1705112/38918848-2901ded0-42ef-11e8-9be9-382b20c74bef.png)

B) You can trace both failed and succesful request by filtering on status code. The example below filters only on status 500, but you can also specify 200-599 to get any HTTP status codes in that range.
![image](https://user-images.githubusercontent.com/1705112/38918789-0116f0d6-42ef-11e8-8a47-999ad1463bd1.png)

The only drawback is that the number of log files is limited per folder, so you need a seperate custom scheduled task/... if you want to keep more.

**Comment by angularsen** [comment]
Ah, I didn't know that. Thanks!
I've added a link to this issue in the README as an alternative approach. Closing this issue.
